const singleItemTestTable = [
  {
    name: "foo",
    description: "standart item updated correctly",
    sellIn: 2,
    quality: 3,
    expectedSellIn: 2 - 1,
    expectedQuality: 3 - 1,
  },
  {
    name: "foo",
    description: "standart item quality is not negative",
    sellIn: 1,
    quality: -1,
    expectedSellIn: 1 - 1,
    expectedQuality: 0,
  },
  {
    name: "foo",
    description: "standart item cant become negative",
    sellIn: 1,
    quality: 0,
    expectedSellIn: 1 - 1,
    expectedQuality: 0,
  },
  {
    name: "foo",
    description: "standart item updated correctly when expired",
    sellIn: 0,
    quality: 5,
    expectedSellIn: 0 - 1,
    expectedQuality: 5 - 1 - 1,
  },
  {
    name: "Aged Brie",
    description: "Aged Brie updates correctly",
    sellIn: 2,
    quality: 4,
    expectedSellIn: 2 - 1,
    expectedQuality: 4 + 1,
  },
  {
    name: "Aged Brie",
    description: "Aged Brie updates correctly when expired",
    sellIn: 0,
    quality: 4,
    expectedSellIn: 0 - 1,
    expectedQuality: 4 + 1 + 1,
  },
  {
    name: "Aged Brie",
    description: "quality less or equal than 50",
    sellIn: 2,
    quality: 50,
    expectedSellIn: 2 - 1,
    expectedQuality: 50,
  },
  {
    name: "Sulfuras, Hand of Ragnaros",
    description: "Sulfuras quality and sell date not updated",
    sellIn: -2,
    quality: 80,
    expectedSellIn: -2,
    expectedQuality: 80,
  },
  {
    name: "Sulfuras, Hand of Ragnaros",
    description: "Sulfuras quality always 80",
    sellIn: 2,
    quality: 50,
    expectedSellIn: 2,
    expectedQuality: 80,
  },
  {
    name: "Backstage passes to a TAFKAL80ETC concert",
    description: "quality updated for more than 10 days prior concert",
    sellIn: 12,
    quality: 2,
    expectedSellIn: 12 - 1,
    expectedQuality: 2 + 1,
  },
  {
    name: "Backstage passes to a TAFKAL80ETC concert",
    description: "quality updated for less than 10 days prior concert",
    sellIn: 9,
    quality: 3,
    expectedSellIn: 9 - 1,
    expectedQuality: 3 + 2,
  },
  {
    name: "Backstage passes to a TAFKAL80ETC concert",
    description: "quality updated for less than 5 days prior concert",
    sellIn: 5,
    quality: 4,
    expectedSellIn: 5 - 1,
    expectedQuality: 4 + 3,
  },
  {
    name: "Backstage passes to a TAFKAL80ETC concert",
    description: "quality not bigger that 50",
    sellIn: 5,
    quality: 49,
    expectedSellIn: 5 - 1,
    expectedQuality: 50,
  },
  {
    name: "Backstage passes to a TAFKAL80ETC concert",
    description: "after concert quality 0",
    sellIn: 0,
    quality: 49,
    expectedSellIn: 0 - 1,
    expectedQuality: 0,
  },
  {
    name: "Conjured item",
    description: "Conjured item degrade twice as fast when up to date",
    sellIn: 2,
    quality: 7,
    expectedSellIn: 2 - 1,
    expectedQuality: 7 - 1 - 1,
  },
  {
    name: "Conjured item",
    description: "Conjured item degrade twice as fast when expired",
    sellIn: 0,
    quality: 7,
    expectedSellIn: 0 - 1,
    expectedQuality: 7 - 1 - 1 - 1 - 1,
  },
];

const multipleItemsTable = [
  {
    description: "different items updated correctly",
    items: [
      {
        name: "foo",
        sellIn: 2,
        quality: 3,
        expectedSellIn: 2 - 1,
        expectedQuality: 3 - 1,
      },
      {
        name: "Conjured item",
        sellIn: 0,
        quality: 7,
        expectedSellIn: 0 - 1,
        expectedQuality: 7 - 1 - 1 - 1 - 1,
      },
      {
        name: "Backstage passes to a TAFKAL80ETC concert",
        sellIn: 9,
        quality: 3,
        expectedSellIn: 9 - 1,
        expectedQuality: 3 + 2,
      },
      {
        name: "Aged Brie",
        sellIn: 2,
        quality: 45,
        expectedSellIn: 2 - 1,
        expectedQuality: 45 + 1,
      },
      {
        name: "Sulfuras, Hand of Ragnaros",
        sellIn: -2,
        quality: 80,
        expectedSellIn: -2,
        expectedQuality: 80,
      },
    ],
  },
];

module.exports = {
  singleItemTestTable,
  multipleItemsTable,
};
